# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "dtypes", :force => true do |t|
    t.column "dtype_name", :string
    t.column "user_id",    :integer
    t.column "twit_id",    :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "twits", :force => true do |t|
    t.column "url",        :string
    t.column "tinyurl",    :string
    t.column "title",      :string
    t.column "user_id",    :integer
    t.column "type_id",    :integer,  :default => 0, :null => false
    t.column "created_at", :datetime
  end

  create_table "types", :force => true do |t|
    t.column "type_name", :string
  end

  create_table "user_types", :force => true do |t|
    t.column "type_name", :string
    t.column "user_id",   :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "twid",                      :integer,                :default => 0, :null => false
    t.column "profile_image_url",         :string
    t.column "twurl",                     :string
    t.column "description",               :string
    t.column "location",                  :string
  end

end
